# Generated by Django 4.1.1 on 2022-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0002_boxer_trener_1_boxer_trener_2_boxer_trener_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viloyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat_nomi', models.CharField(max_length=200)),
            ],
        ),
    ]
