# Generated by Django 4.1.1 on 2022-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0004_alter_boxer_viloyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viloyatlar',
            name='viloyat_nomi',
        ),
        migrations.AddField(
            model_name='viloyatlar',
            name='viloyat_nomi_en',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='viloyatlar',
            name='viloyat_nomi_ru',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='viloyatlar',
            name='viloyat_nomi_uz',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
