# Generated by Django 4.1.1 on 2022-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0006_alter_viloyatlar_viloyat_nomi_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_types_of_chempion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
