# Generated by Django 4.1.1 on 2022-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0007_all_types_of_chempion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_types_of_chempion',
            name='type',
        ),
        migrations.AddField(
            model_name='all_types_of_chempion',
            name='type_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='all_types_of_chempion',
            name='type_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='all_types_of_chempion',
            name='type_uz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
