# Generated by Django 4.1.1 on 2022-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0008_remove_all_types_of_chempion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='chempionlik_yutugi',
            field=models.ManyToManyField(to='boxing_app.all_types_of_chempion'),
        ),
    ]
