# Generated by Django 4.1.1 on 2022-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0009_boxer_chempionlik_yutugi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxer',
            name='chempionlik_yutugi',
        ),
        migrations.AddField(
            model_name='boxer',
            name='unvoni',
            field=models.ManyToManyField(to='boxing_app.all_types_of_chempion'),
        ),
    ]
