# Generated by Django 4.1.1 on 2022-09-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0010_remove_boxer_chempionlik_yutugi_boxer_unvoni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxer',
            name='unvoni',
        ),
        migrations.AddField(
            model_name='boxer',
            name='unvoni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxing_app.all_types_of_chempion'),
        ),
    ]
