# Generated by Django 4.1.1 on 2022-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxing_app', '0011_remove_boxer_unvoni_boxer_unvoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='nokaut',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boxer',
            name='qaror',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boxer',
            name='taqdim_etish_orqali',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boxer',
            name='umumiy_janglari_soni',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boxer',
            name='yutganlari',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='boxer',
            name='yutqazganlari',
            field=models.CharField(default='', max_length=200),
        ),
    ]
